### ISSUE TITLE
Integrated into core?

### ISSUE THREAD

**Issue by magnolia61** [3sd/civicrm-recalculate-recipients#12]
Am I correct or mistaken that this functionality has recently been integrated into CiviCRM core.
If not, would it be wise to propose?

**Comment by michaelmcandrew** [comment]
Personally I would like to see it in core, though we'd have to find a solution to https://github.com/3sd/civicrm-recalculate-recipients#heath-warning before that could happen.

There are some use cases for which what this extension does isn't the desired behaviour: see https://lists.civicrm.org/lists/arc/civicrm-dev/2017-12/msg00012.html for more details.

One sane approach to adding it to core would be to carry out a poll to see which is the most common use case and make it configurable with the most popular response as the default behaviour.

**Comment by magnolia61** [comment]
I have asked this before and now in 2022 asking again:
This extension still adds to the functionality that is in core?
Core still does not recalculate smartgroup recipients at the time of sending?

**Comment by michaelmcandrew** [comment]
AFAIK it is not yet in core.

**Comment by michaelmcandrew** [comment]
Closing this issue as I am archiving this repo - please open an issue on https://lab.civicrm.org/extensions/civicrm-recalculate-recipients and reference this issue if you'd like to continue the discussion.
