### ISSUE TITLE
Recalculate Recipients extension causes A/B Mailings to send all emails to the Mailing A group and 0 emails to Mailing B and C groups

### ISSUE THREAD

**Issue by agileware-justin** [3sd/civicrm-recalculate-recipients#17]
Recalculate Recipients extension causes A/B Mailings to send all emails to the Mailing A group and 0 emails to Mailing B and C groups.

I mistakenly thought this was a core CiviCRM bug, but after more detailed testing and reviewing the enabled extensions was able to identify that this extension was causing the issue. Details of this bug report and the discussion can be seen https://lab.civicrm.org/dev/core/-/issues/2810

When the Recalculate Recipients extension is enabled, the A/B Mailing will only send Mailing A to all Recipients, not a percentage of the recipients. Mailing B and Final Mailing are not sent, they have zero recipients..

Regardless of whether the Final Mailing is based on Mailing A or Mailing B, **no recipients are set** and the Final Mailing is not sent.

Using CiviCRM 5.40.4

Below is a series of screenshots of each step in the process.

Selecting the target group percentage.

![Screenshot_20210901_162830](https://user-images.githubusercontent.com/58866555/133867576-8701bcf7-9502-492c-8a00-22c25c5ed14a.png)

Mailing A and B scheduled.

![Screenshot_20210901_162944](https://user-images.githubusercontent.com/58866555/133867574-762f0656-b8a8-4237-b3a6-9e50c2622e1e.png)

Mailing A and B sent.

![Screenshot_20210901_163011](https://user-images.githubusercontent.com/58866555/133867573-9e8c9ec0-b218-43db-aa21-44fa588e6a47.png)

Final mailing selected and sent.

![Screenshot_20210901_163602](https://user-images.githubusercontent.com/58866555/133867572-add37f95-bf12-452e-a52c-e0def6eeea4d.png)

Agileware Ref: CIVICRM-1828

**Comment by michaelmcandrew** [comment]
Hi @jusfreeman - thanks for this report!

We don't have the resources to fix this at the moment. We would potentially have time toward the end of this year though I don't think it will be a priority I am afraid. Some funding would help us to prioritize. And/or a patch would be welcome, of course :)

**Comment by agileware-justin** [comment]
@michaelmcandrew all good and understand completely, thought it worth reporting - just in case anyone else hits this curly one.

**Comment by michaelmcandrew** [comment]
Yes - and thanks, appreciate the report.

**Comment by michaelmcandrew** [comment]
Closing this issue as I am archiving this repo - please open an issue on https://lab.civicrm.org/extensions/civicrm-recalculate-recipients and reference this issue if you'd like to continue the discussion.
