### ISSUE TITLE
If there are more than 25 scheduled mailings only the first 25 are recalculated

### ISSUE THREAD

**Issue by lolcodeca** [3sd/civicrm-recalculate-recipients#5]
The API call to get the MailingJob's uses the default limit of 25 results. If there are more than 25 this is a problem. Due to corrupt data in the system I am working with there are 63 jobs outstanding.

**Comment by michaelmcandrew** [comment]
Thanks for reporting this @lolcodeca 

I pushed https://github.com/3sd/civicrm-recalculate-recipients/commit/06f911ec42d4629f8c2195ff5cc1de4a738c9815 which sets the limit to 0.

This seems reasonable given that this is a cron job. If it does turn out to be a problem (I am struggling to think of a use case where it would be (though I have learned to expect the unexpected in CiviLand!) we can come up with a more sophisticated queue or similar.

**Comment by michaelmcandrew** [comment]
feel free to re-open if you disagree...
