### ISSUE TITLE
If a Mailing is deleted after the mailing has been started an exception will occur

### ISSUE THREAD

**Issue by lolcodeca** [3sd/civicrm-recalculate-recipients#6]
If a Mailing is deleted after the mailing has been started an exception will occur on this line. This was an issue in the system I am working with due to invalid data. It just needs to be wrapped in a try-catch.

`$mailing = civicrm_api3('mailing', 'getsingle', ['id' => $mailing_id]);`

**Comment by michaelmcandrew** [comment]
fixed with https://github.com/3sd/civicrm-recalculate-recipients/commit/c796823520ff795dd79ce1f5a302ccfe4e14e882. thanks @lolcodeca  :)
