### ISSUE TITLE
Too many parameters in call to CRM_Mailing_BAO_Mailing::getRecipients

### ISSUE THREAD

**Issue by lolcodeca** [3sd/civicrm-recalculate-recipients#7]
As mentioned by Monish in chat: https://chat.civicrm.org/civicrm/pl/3y5s4uxcof81ur553cmeu85tdo there are too many parameters to this function call.

**Comment by michaelmcandrew** [comment]
thanks for reporting @lolcodeca (and @monishdeb)

following [monish's refactor](https://github.com/civicrm/civicrm-core/commit/6dd717a6572e06770dd7b518ba5b8f264c05944e) I've pushed this commit https://github.com/3sd/civicrm-recalculate-recipients/commit/37b0cd79fd3ee147cf4fe94c55184fe476e1be8c which should fix the problem (and also removes a now unecessary api call).
